CREATE TABLE audit_logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entity_type     VARCHAR(100)                            NOT NULL,
    entity_id       VARCHAR(100)                            NOT NULL,
    action          VARCHAR(10)                             NOT NULL,
    actor_id        BIGINT,
    actor_role      VARCHAR(30)                             NOT NULL,
    before_snapshot JSONB,
    after_snapshot  JSONB,
    timestamp       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE availability
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id       BIGINT                                  NOT NULL,
    availability_type VARCHAR(10)                             NOT NULL,
    is_available      BOOLEAN DEFAULT TRUE                    NOT NULL,
    day_of_week       VARCHAR(10),
    start_time        time WITHOUT TIME ZONE,
    end_time          time WITHOUT TIME ZONE,
    start_date        date,
    end_date          date,
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT availability_pkey PRIMARY KEY (id)
);

CREATE TABLE departments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(150)                            NOT NULL,
    location_id BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT departments_pkey PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                 BIGINT                                  NOT NULL,
    phone                   VARCHAR(30),
    employment_type         VARCHAR(20)                             NOT NULL,
    department_id           BIGINT,
    primary_location_id     BIGINT,
    contracted_weekly_hours numeric(5, 2) DEFAULT 0                 NOT NULL,
    hire_date               date                                    NOT NULL,
    is_active               BOOLEAN       DEFAULT TRUE              NOT NULL,
    skills                  JSONB         DEFAULT '[]'              NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT employees_pkey PRIMARY KEY (id)
);

CREATE TABLE leave_requests
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    leave_type  VARCHAR(10)                             NOT NULL,
    start_date  date                                    NOT NULL,
    end_date    date                                    NOT NULL,
    reason      TEXT,
    status      VARCHAR(20) DEFAULT 'PENDING'           NOT NULL,
    reviewed_by BIGINT,
    hr_note     VARCHAR(500),
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()     NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()     NOT NULL,
    CONSTRAINT leave_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE locations
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(150)                            NOT NULL,
    address                 VARCHAR(300)                            NOT NULL,
    max_headcount_per_shift INTEGER                                 NOT NULL,
    is_active               BOOLEAN DEFAULT TRUE                    NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT locations_pkey PRIMARY KEY (id)
);

CREATE TABLE manager_locations
(
    manager_id  BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    CONSTRAINT manager_locations_pkey PRIMARY KEY (manager_id, location_id)
);

CREATE TABLE notifications
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipient_id   BIGINT                                  NOT NULL,
    type           VARCHAR(30)                             NOT NULL,
    message        TEXT                                    NOT NULL,
    reference_id   BIGINT,
    reference_type VARCHAR(50),
    is_read        BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE shift_assignments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shift_id        BIGINT                                  NOT NULL,
    employee_id     BIGINT                                  NOT NULL,
    assigned_by     BIGINT                                  NOT NULL,
    assigned_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()      NOT NULL,
    override_reason TEXT,
    status          VARCHAR(20) DEFAULT 'ASSIGNED'          NOT NULL,
    version         INTEGER     DEFAULT 0                   NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()      NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()      NOT NULL,
    CONSTRAINT shift_assignments_pkey PRIMARY KEY (id)
);

CREATE TABLE shifts
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location_id       BIGINT                                  NOT NULL,
    department_id     BIGINT                                  NOT NULL,
    shift_date        date                                    NOT NULL,
    start_time        time WITHOUT TIME ZONE                      NOT NULL,
    end_time          time WITHOUT TIME ZONE                      NOT NULL,
    required_skill    VARCHAR(100),
    minimum_headcount INTEGER     DEFAULT 1                   NOT NULL,
    status            VARCHAR(20) DEFAULT 'DRAFT'             NOT NULL,
    created_by        BIGINT                                  NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()   NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()   NOT NULL,
    CONSTRAINT shifts_pkey PRIMARY KEY (id)
);

CREATE TABLE swap_requests
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    requester_assignment_id BIGINT                                         NOT NULL,
    target_assignment_id    BIGINT                                         NOT NULL,
    requested_by            BIGINT                                         NOT NULL,
    target_employee_id      BIGINT                                         NOT NULL,
    status                  VARCHAR(30) DEFAULT 'PENDING_MANAGER_APPROVAL' NOT NULL,
    reviewed_by             BIGINT,
    manager_note            VARCHAR(500),
    created_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    updated_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    CONSTRAINT swap_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name     VARCHAR(150)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    role          VARCHAR(30)                             NOT NULL,
    is_active     BOOLEAN DEFAULT TRUE                    NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
